USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_TempTabs', 'U') IS NOT NULL
	DROP TABLE POS_TempTabs
GO

CREATE TABLE POS_TempTabs
(
	TabID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	TabName VARCHAR(50) NOT NULL,
	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)