USE [TMIS_Development]
GO

IF OBJECT_ID('POS_Logs', 'U') IS NOT NULL
	DROP TABLE POS_Logs
GO

CREATE TABLE POS_Logs
(
	AuditLogID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	[Action] VARCHAR(255) NOT NULL,
	ItemID INT NULL,
	Item VARCHAR(255) NULL,
	FK_UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
	ActionDate DATETIME NOT NULL,
)