USE [TMIS_Development]
GO

IF OBJECT_ID('POS_SlipPrinters', 'U') IS NOT NULL
	DROP TABLE POS_SlipPrinters
GO

CREATE TABLE POS_SlipPrinters
(
	SlipPrinterID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_LocationID INT NOT NULL FOREIGN KEY REFERENCES POS_Locations (LocationID),
	CostCenterID INT NULL FOREIGN KEY REFERENCES POS_CostCenters (CostCenterID),

	[Name] VARCHAR(50) NOT NULL,
	Model VARCHAR(50) NOT NULL,
	IpAddress VARCHAR(20) NOT NULL,
	[Port] INT NOT NULL,

	IsDefault BIT NOT NULL DEFAULT 0,
	IsActive BIT NOT NULL,
	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	FK_UpdatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateCreated DATETIME NOT NULL DEFAULT GETDATE(),
	DateUpdated DATETIME NOT NULL DEFAULT GETDATE()
)