USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_TablineSubstitutes', 'U') IS NOT NULL
	DROP TABLE POS_TablineSubstitutes
GO

CREATE TABLE POS_TablineSubstitutes
(
	POS_TablineSubstituteID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_ParentTabLineID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_TabLines (TabLineID),
	FK_SubstituionTabLineID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_TabLines (TabLineID),
)