USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_VoidLogs', 'U') IS NOT NULL
	DROP TABLE POS_VoidLogs
GO

CREATE TABLE POS_VoidLogs
(
	VoidLogID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_TabID UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES POS_Tabs (TabID),
	FK_TabLineID UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES POS_TabLines (TabLineID),
	VoidedBy VARCHAR(255) NOT NULL,

	Note VARCHAR(MAX) NULL,

	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)