USE [TMIS_Development]
GO

IF OBJECT_ID('POS_TabLines', 'U') IS NOT NULL
	DROP TABLE POS_TabLines
GO

CREATE TABLE POS_TabLines
(
	TabLineID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_TabID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_Tabs (TabID),
	FK_ProductID INT NOT NULL FOREIGN KEY REFERENCES POS_Products(ProductID),
	FK_PriceCodeID INT NOT NULL FOREIGN KEY REFERENCES POS_PriceCodes (PriceCodeID),

	FK_PointerID UNIQUEIDENTIFIER NULL,

	UnitCostExcl DECIMAL (18, 4) NOT NULL,
	Vat DECIMAL(18, 4) NOT NULL,
	UnitCostIncl DECIMAL (18, 4) NOT NULL,

	[Product] VARCHAR(50) NOT NULL,
	Quantity DECIMAL (18, 4) NOT NULL,
	Discount DECIMAL (18, 4) NULL,
	DiscountPerc INT NULL,
	IsVoided BIT NOT NULL,
	Notes VARCHAR(MAX) NULL,
	AutoNotes VARCHAR(MAX) NULL,

	CreatedBy VARCHAR(255) NOT NULL,

	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)