USE [TMIS_Development]
GO

IF OBJECT_ID('POS_TabLineExtras', 'U') IS NOT NULL
	DROP TABLE POS_TabLineExtras
GO

CREATE TABLE POS_TabLineExtras
(
	TabLineExtraID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_TabLineID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_TabLines (TabLineID),
	FK_ProductID INT NOT NULL FOREIGN KEY REFERENCES POS_Products(ProductID),

	[Product] VARCHAR(255) NOT NULL
)