USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID ('POS_SlipTypes', 'U') IS NOT NULL
	DROP TABLE POS_SlipTypes
GO

CREATE TABLE POS_SlipTypes
(
	SlipTypeID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	-- Tab, Invoice, Order, Picking, etc
	SlipType VARCHAR(15) NOT NULL,
	-- TAB1, TAB2, TAB3, INV1, INV2, KOT, RUNNER, PICK1, PICK2
	SlipCode VARCHAR(20) NOT NULL,
	[Description] VARCHAR(255) NULL,
	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	FK_UpdatedUserID INT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateCreated DATETIME NOT NULL DEFAULT (GETDATE()),
	DateUpdated DATETIME NULL
)