USE [TMIS_Development]
GO

IF OBJECT_ID('POS_MenuItems', 'U') IS NOT NULL
	DROP TABLE POS_MenuItems
GO

CREATE TABLE POS_MenuItems
(
	MenuItemID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_MenuID INT NULL FOREIGN KEY REFERENCES POS_Menus (MenuID),
	Item VARCHAR(50) NOT NULL,
	[Description] VARCHAR(255) NULL,
	FK_MenuItemID INT NULL FOREIGN KEY REFERENCES POS_MenuItems (MenuItemID),
	DateCreated DATETIME NOT NULL,
	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateUpdated DATETIME NOT NULL,
	FK_UpdatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),

	CONSTRAINT MenuID_ItemName UNIQUE (FK_MenuID, Item)
)