USE [TMIS_Development]
GO

IF OBJECT_ID('POS_StockRequests', 'U') IS NOT NULL
	DROP TABLE POS_StockRequests
GO

CREATE TABLE POS_StockRequests
(
	StockRequestID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	RefNumber VARCHAR(50) NULL,
	FK_FromDebtorID INT NOT NULL FOREIGN KEY REFERENCES POS_Locations(LocationID),
	FK_ToDebtorID INT NOT NULL FOREIGN KEY REFERENCES POS_Locations(LocationID),
	FK_OrderStatusID INT NOT NULL FOREIGN KEY REFERENCES POS_OrderStatus(OrderStatusID),
	FK_UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
	ManagerNotes VARCHAR(255) NULL,
	Notes VARCHAR(MAX) NULL,
	DateOrdered DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL,
	FK_ApprovedByUserID INT NULL FOREIGN KEY REFERENCES Users(UserID),
	DateApproved DATETIME NULL
)
