USE [TMIS_Development]
GO

IF OBJECT_ID ('POS_TaxTypes', 'U') IS NOT NULL
	DROP TABLE POS_TaxTypes
GO

CREATE TABLE POS_TaxTypes
(
	TaxTypeID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	TaxName VARCHAR(255) NOT NULL,
	TaxPercentage INT NOT NULL,
	ValidFrom DATETIME NULL,
	ValidTo DATETIME NULL,
	IsActive BIT NOT NULL,
	DateCreated DATETIME NOT  NULL,
	DateUpdated DATETIME NOT NULL
)