USE [TMIS_POS_Demo]
GO

IF OBJECT_ID('POS_LocationCurrencies', 'U') IS NOT NULL
	DROP TABLE POS_LocationCurrencies
GO

CREATE TABLE POS_LocationCurrencies
(
	LocationCurrencyID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_CurrencyID INT NOT NULL FOREIGN KEY REFERENCES Currencies (CurrencyID),
	FK_LocationID INT NULL FOREIGN KEY REFERENCES POS_Locations (LocationID),
	IsActive BIT NOT NULL,
	DateCreated DATETIME NOT NULL DEFAULT GETDATE(),
	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateUpdated DATETIME NOT NULL DEFAULT GETDATE(),
	FK_UpdatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
)