USE [TMIS_Development]
GO

IF OBJECT_ID('POS_StockTransfers', 'U') IS NOT NULL
	DROP TABLE POS_StockTransfers
GO

CREATE TABLE POS_StockTransfers
(
	StockTransferID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	RefNumber VARCHAR(50) NULL,
	FK_FromDebtorID INT NOT NULL FOREIGN KEY REFERENCES Debtors(DebtorID),
	FK_ToDebtorID INT NOT NULL FOREIGN KEY REFERENCES Debtors(DebtorID),
	FK_OrderStatusID INT NOT NULL FOREIGN KEY REFERENCES POS_OrderStatus(OrderStatusID),
	FK_UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
	DateTransfered DATETIME NOT NULL,
	Notes VARCHAR(MAX) NULL,
)