USE [TMIS_Development]
GO

IF OBJECT_ID('POS_InvoiceLines', 'U') IS NOT NULL
	DROP TABLE POS_InvoiceLines
GO

CREATE TABLE POS_InvoiceLines
(
	InvoiceLineID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_InvoiceTabID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_InvoiceTabs (InvoiceTabID),
	FK_ProductID INT NOT NULL,
	[Product] VARCHAR(100) NOT NULL,
	Quantity DECIMAL(18, 4) NOT NULL,
	LineDiscount DECIMAL(18, 4) NOT NULL,
	LineTotalExcl DECIMAL(18, 4) NOT NULL,
	LineTotalVat DECIMAL(18, 4) NOT NULL,
	LineTotalIncl DECIMAL(18, 4) NOT NULL,
	Guests VARCHAR(100) NULL,
	SyncedToServer BIT NOT NULL
)