USE [TMIS_Development]
GO

IF OBJECT_ID('POS_Menus', 'U') IS NOT NULL
	DROP TABLE POS_Menus
GO

CREATE TABLE POS_Menus
(
	MenuID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	MenuName VARCHAR(50) NOT NULL,
	IsActive BIT NOT NULL,
	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)