USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_TempTabLines', 'U') IS NOT NULL
	DROP TABLE POS_TempTabLines
GO

CREATE TABLE POS_TempTabLines
(
	TabID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_TabID INT NOT NULL FOREIGN KEY REFERENCES POS_TempTabs (TabID),
	FK_ProductID INT NOT NULL FOREIGN KEY REFERENCES POS_Products (POS_ProductID),
	Quantity INT NOT NULL,
	IsOrdered BIT NOT NULL,
	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)