USE [TMIS_Development]
GO

IF OBJECT_ID ('POS_CostCenterProducts', 'U') IS NOT NULL
	DROP TABLE POS_CostCenterProducts
GO

CREATE TABLE POS_CostCenterProducts
(
	CostCenterProductID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_ProductID INT NOT NULL FOREIGN KEY REFERENCES POS_Products (ProductID),
	FK_CostCenterID INT NOT NULL FOREIGN KEY REFERENCES POS_CostCenters (CostCenterID),
	FK_TaxTypeID INT NOT NULL FOREIGN KEY REFERENCES POS_TaxTypes (TaxTypeID),
	
	[Value] DECIMAL(18, 4) NOT NULL,
	Vat DECIMAL(18, 4) NOT NULL,
	ItemPrice DECIMAL(18, 4) NOT NULL,

	FK_SellUnitID INT NOT NULL FOREIGN KEY REFERENCES POS_Units (UnitID),
	QuantityOnHand DECIMAL(18, 4) NOT NULL,
	IsAvailable BIT NOT NULL,
	IsActive BIT NOT NULL,

	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	FK_UpdatedUserID INT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateCreated DATETIME NOT NULL DEFAULT (GETDATE()),
	DateUpdated DATETIME NULL DEFAULT (GETDATE())
	CONSTRAINT product_cost_id UNIQUE (FK_ProductID, FK_CostcenterID)
)