USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_CashUpLines', 'U') IS NOT NULL
	DROP TABLE POS_CashUpLines
GO

CREATE TABLE POS_CashUpLines
(
    CashUpPaymentTypeID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
    FK_CashUpID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_CashUpHeaders(CashUpHeaderID),
    FK_PaymentTypeID INT NOT NULL FOREIGN KEY REFERENCES POS_PaymentTypes(PaymentTypeID),

    SystemAmount DECIMAL(18, 4) NOT NULL DEFAULT 0,
    CountedAmount DECIMAL(18, 4) NOT NULL DEFAULT 0,
    VarianceAmount DECIMAL(18, 4) NULL,

    Notes VARCHAR(MAX) NULL,
    DateCreated DATETIME NOT NULL DEFAULT GETDATE(),
    DateUpdated DATETIME NOT NULL DEFAULT GETDATE()
);