USE [TMIS_Development]
GO

IF OBJECT_ID('POS_DebtorMenus', 'U') IS NOT NULL
	DROP TABLE POS_DebtorMenus
GO

CREATE TABLE POS_DebtorMenus
(
	DebtorMenuID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_LocationID INT NOT NULL FOREIGN KEY REFERENCES POS_Locations (LocationID),
	FK_CostCenterID INT NULL FOREIGN KEY REFERENCES POS_CostCenters (CostCenterID),
	FK_MenuID INT NULL FOREIGN KEY REFERENCES POS_Menus (MenuID),
	MenuName VARCHAR(50) NOT NULL,
	ValidFrom DATETIME NULL,
	ValidTo DATETIME NULL,
	IsActive BIT NOT NULL,
	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)