USE [TMIS_Development]
GO

IF OBJECT_ID('POS_MenuItemProducts', 'U') IS NOT NULL
	DROP TABLE POS_MenuItemProducts
GO

CREATE TABLE POS_MenuItemProducts
(
	MenuItemProductID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_MenuItemID INT NULL FOREIGN KEY REFERENCES POS_MenuItems (MenuItemID),
	FK_ProductID INT NOT NULL FOREIGN KEY REFERENCES POS_Products (ProductID),
	DisplayOrder INT NOT NULL DEFAULT 0,
	DateCreated DATETIME NOT NULL,
	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateUpdated DATETIME NOT NULL,
	FK_UpdatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
)