USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_Images', 'U') IS NOT NULL
	DROP TABLE POS_Images
GO

CREATE TABLE POS_Images
(
	ImageID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_ImageCategoryID INT NOT NULL FOREIGN KEY REFERENCES POS_ImageCategories (ImageCategoryID),
	FK_ItemID INT NOT NULL,
	FileSystemPath VARCHAR(255) NOT NULL,
	RelativePath VARCHAR(255) NOT NULL,
	ImageName VARCHAR(255) NOT NULL,
	FileExtension VARCHAR(255) NOT NULL,
	ImageUrl VARCHAR(255) NOT NULL,
	LocalUrl VARCHAR(255) NOT NULL,
	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)