USE [TMIS_Development]
GO

IF OBJECT_ID ('POS_Units', 'U') IS NOT NULL
	DROP TABLE POS_Units
GO

CREATE TABLE POS_Units
(
	UnitID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	Unit VARCHAR(255) NOT NULL,
	Symbol VARCHAR(10) NULL,
	BC_ID VARCHAR(255) NULL,
	IsActive BIT NOT NULL,
	DateCreated DATETIME NOT  NULL,
	DateUpdated DATETIME NOT NULL
)

