USE [TMIS_Development]
GO

IF OBJECT_ID('POS_Locations', 'U') IS NOT NULL
	DROP TABLE POS_Locations
GO

CREATE TABLE POS_Locations
(
	LocationID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_CurrencyID INT NULL FOREIGN KEY REFERENCES Currencies (CurrencyID),
	BC_ID VARCHAR(255) NULL,
	ShortCode VARCHAR(50) NULL,
	[Name] VARCHAR(255) NOT NULL,
	IsActive BIT NOT NULL,
	DateCreated DATETIME NOT NULL DEFAULT GETDATE(),
	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateUpdated DATETIME NOT NULL DEFAULT GETDATE(),
	FK_UpdatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
)