USE [TMIS_Development]
GO

IF OBJECT_ID('POS_InvoiceTabs', 'U') IS NOT NULL
	DROP TABLE POS_InvoiceTabs
GO

CREATE TABLE POS_InvoiceTabs
(
	InvoiceTabID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_InvoiceHeaderID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_InvoiceHeaders(InvoiceHeaderID),
	FK_TabID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_Tabs(TabID),

	TabGratuity DECIMAL(18, 4) NOT NULL,
	TabDiscount DECIMAL(18, 4) NOT NULL,
	TabTotalExcl DECIMAL(18, 4) NOT NULL,
	TabTotalVat DECIMAL(18, 4) NOT NULL,
	TabTotalIncl DECIMAL(18, 4) NOT NULL,

	TabDateOpened DATETIME NOT NULL,
	TabDateClosed DATETIME NOT NULL,
	SyncedToServer BIT NOT NULL
)