USE [TMIS_POS_Demo]
GO

IF OBJECT_ID ('POS_Settings', 'U') IS NOT NULL
	DROP TABLE POS_Settings
GO

CREATE TABLE POS_Settings
(
	SettingID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	CompanyName VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	HeadOfficeNo VARCHAR(255) NOT NULL,
	FK_CurrencyID INT NOT NULL FOREIGN KEY REFERENCES Currencies(CurrencyID),
	DateCreated DATETIME NOT  NULL,
	DateUpdated DATETIME NOT NULL
)

