USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_Arrivals', 'U') IS NOT NULL
	DROP TABLE POS_Arrivals
GO

CREATE TABLE POS_Arrivals
(
    ArrivalID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_GuestID INT NOT NULL FOREIGN KEY REFERENCES Guests(GuestID),

	CheckedInBy VARCHAR(255),
    CheckInDate DATETIME NOT NULL,
	CheckedOutBy VARCHAR(255),
    CheckOutDate DATETIME NULL,
	CONSTRAINT GuestsID UNIQUE (FK_GuestID)
)