USE [TMIS_Development]
GO

IF OBJECT_ID('POS_PurchaseOrders', 'U') IS NOT NULL
	DROP TABLE POS_PurchaseOrders
GO

CREATE TABLE POS_PurchaseOrders
(
	PurchaseOrderID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	OrderNumber VARCHAR(50) NOT NULL,
	FK_SupplierID INT NOT NULL FOREIGN KEY REFERENCES Creditors(CreditorID),
	FK_DebtorID INT NOT NULL FOREIGN KEY REFERENCES Debtors(DebtorID),
	FK_CostCenterID INT NULL FOREIGN KEY REFERENCES POS_CostCenters(CostCenterID),
	FK_OrderStatusID INT NOT NULL FOREIGN KEY REFERENCES POS_OrderStatus(OrderStatusID),
	FK_UserID INT NOT NULL FOREIGN KEY REFERENCES Users(UserID),
	Notes VARCHAR(MAX) NULL,
	ManagerNotes VARCHAR(MAX) NULL,
	DateOrdered DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)