USE [TMIS_Development]
GO

IF OBJECT_ID('POS_TabLineGuests', 'U') IS NOT NULL
	DROP TABLE POS_TabLineGuests
GO

CREATE TABLE POS_TabLineGuests
(
	TabLineGuestID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	FK_TabLineID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES POS_TabLines (TabLineID),
	FK_GuestID INT NOT NULL FOREIGN KEY REFERENCES Guests(GuestID),
	Note VARCHAR(MAX) NULL,
	DateUpdated DATETIME NOT NULL
)