USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID('POS_Tabs', 'U') IS NOT NULL
	DROP TABLE POS_Tabs
GO

CREATE TABLE POS_Tabs
(
	TabID UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,

	FK_LocationID INT NOT NULL FOREIGN KEY REFERENCES POS_Locations(LocationID),
	FK_AccountID UNIQUEIDENTIFIER NULL FOREIGN KEY REFERENCES POS_Accounts(AccountID),
	FK_CostCenterID INT NULL FOREIGN KEY REFERENCES POS_CostCenters(CostCenterID),
	FK_PaymentTypeID INT NULL FOREIGN KEY REFERENCES POS_PaymentTypes(PaymentTypeID),
	FK_CurrencyID INT NULL FOREIGN KEY REFERENCES Currencies(CurrencyID),

	TabName VARCHAR(50) NULL,
	TableName INT NULL,
	NoOfGuests INT NULL,
	Gratuity DECIMAL (18, 4) NULL,
	GratuityPerc INT NULL,
	Discount DECIMAL (18, 4) NULL,
	DiscountPerc INT NULL,
	IsVoided BIT NOT NULL,
	VoidNote VARCHAR(MAX) NULL,
	IsPaid BIT NOT NULL,
	AmountPaid DECIMAL(18, 4) NOT NULL,
	AmountDue DECIMAL(18, 4) NULL,
	VatTotal DECIMAL (18, 4) NULL,
	CurrentExchangeRate DECIMAL(18, 8) NULL,
	PaymentDate DATETIME NULL,
	ClosedDate DATETIME NULL,
	AdditionalInfo VARCHAR(255) NULL,

	CreatedBy VARCHAR(255) NOT NULL,

	DateCreated DATETIME NOT NULL,
	DateUpdated DATETIME NOT NULL
)