using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace POS_Common.Enums
{
    public class CurrencySymbol
    {
        public static string GetSymbol(string currencyCode)
        {
            if (string.IsNullOrWhiteSpace(currencyCode))
                return string.Empty;

            switch (currencyCode.ToUpper())
            {
                case "AED": return "د.إ";
                case "AFN": return "؋";
                case "ALL": return "L";
                case "AMD": return "֏";
                case "ANG": return "ƒ";
                case "AOA": return "Kz";
                case "ARS": return "$";
                case "AUD": return "$";
                case "AWG": return "ƒ";
                case "AZN": return "₼";
                case "BAM": return "KM";
                case "BBD": return "$";
                case "BDT": return "৳";
                case "BGN": return "лв";
                case "BHD": return ".د.ب";
                case "BIF": return "FBu";
                case "BMD": return "$";
                case "BND": return "$";
                case "BOB": return "Bs.";
                case "BRL": return "R$";
                case "BSD": return "$";
                case "BTN": return "Nu.";
                case "BWP": return "P";
                case "BYN": return "Br";
                case "BZD": return "$";
                case "CAD": return "$";
                case "CDF": return "FC";
                case "CHF": return "CHF";
                case "CLP": return "$";
                case "CNY": return "¥";
                case "COP": return "$";
                case "CRC": return "₡";
                case "CUC": return "$";
                case "CUP": return "$";
                case "CVE": return "$";
                case "CZK": return "Kč";
                case "DJF": return "Fdj";
                case "DKK": return "kr";
                case "DOP": return "RD$";
                case "DZD": return "دج";
                case "EGP": return "£";
                case "ERN": return "Nfk";
                case "ETB": return "Br";
                case "EUR": return "€";
                case "FJD": return "$";
                case "FKP": return "£";
                case "GBP": return "£";
                case "GEL": return "₾";
                case "GHS": return "₵";
                case "GIP": return "£";
                case "GMD": return "D";
                case "GNF": return "FG";
                case "GTQ": return "Q";
                case "GYD": return "$";
                case "HKD": return "$";
                case "HNL": return "L";
                case "HRK": return "€";
                case "HTG": return "G";
                case "HUF": return "Ft";
                case "IDR": return "Rp";
                case "ILS": return "₪";
                case "INR": return "₹";
                case "IQD": return "ع.د";
                case "IRR": return "﷼";
                case "ISK": return "kr";
                case "JMD": return "$";
                case "JOD": return "د.ا";
                case "JPY": return "¥";
                case "KES": return "KSh";
                case "KGS": return "с";
                case "KHR": return "៛";
                case "KMF": return "CF";
                case "KPW": return "₩";
                case "KRW": return "₩";
                case "KWD": return "د.ك";
                case "KYD": return "$";
                case "KZT": return "₸";
                case "LAK": return "₭";
                case "LBP": return "ل.ل";
                case "LKR": return "Rs";
                case "LRD": return "$";
                case "LSL": return "L";
                case "LYD": return "ل.د";
                case "MAD": return "د.م.";
                case "MDL": return "L";
                case "MGA": return "Ar";
                case "MKD": return "ден";
                case "MMK": return "Ks";
                case "MNT": return "₮";
                case "MOP": return "MOP$";
                case "MUR": return "₨";
                case "MVR": return "Rf";
                case "MWK": return "MK";
                case "MXN": return "$";
                case "MYR": return "RM";
                case "MZN": return "MT";
                case "NAD": return "$";
                case "NGN": return "₦";
                case "NIO": return "C$";
                case "NOK": return "kr";
                case "NPR": return "₨";
                case "NZD": return "$";
                case "OMR": return "﷼";
                case "PAB": return "B/.";
                case "PEN": return "S/";
                case "PGK": return "K";
                case "PHP": return "₱";
                case "PKR": return "₨";
                case "PLN": return "zł";
                case "PYG": return "₲";
                case "QAR": return "﷼";
                case "RON": return "lei";
                case "RSD": return "дин";
                case "RUB": return "₽";
                case "RWF": return "FRw";
                case "SAR": return "﷼";
                case "SBD": return "$";
                case "SCR": return "₨";
                case "SDG": return "£";
                case "SEK": return "kr";
                case "SGD": return "$";
                case "SHP": return "£";
                case "SLL": return "Le";
                case "SOS": return "S";
                case "SRD": return "$";
                case "SSP": return "£";
                case "SYP": return "£";
                case "SZL": return "E";
                case "THB": return "฿";
                case "TJS": return "SM";
                case "TMT": return "m";
                case "TND": return "د.ت";
                case "TOP": return "T$";
                case "TRY": return "₺";
                case "TTD": return "$";
                case "TWD": return "NT$";
                case "TZS": return "TSh";
                case "UAH": return "₴";
                case "UGX": return "USh";
                case "USD": return "$";
                case "UYU": return "$U";
                case "UZS": return "soʻm";
                case "VND": return "₫";
                case "VUV": return "VT";
                case "WST": return "WS$";
                case "XAF": return "FCFA";
                case "XCD": return "$";
                case "XOF": return "CFA";
                case "XPF": return "₣";
                case "YER": return "﷼";
                case "ZAR": return "R";
                case "ZMW": return "ZK";
                case "ZWL": return "Z$";
                default: return currencyCode;
            }
        }
    }
}
