USE [TMIS_BlueSafaris]
GO

IF OBJECT_ID ('POS_ServedAsProducts', 'U') IS NOT NULL
	DROP TABLE POS_ServedAsProducts
GO

CREATE TABLE POS_ServedAsProducts
(
	ServedAsProductID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FK_ProductID INT NOT NULL FOREIGN KEY REFERENCES POS_Products (ProductID),
	FK_ServedAsID INT NOT NULL FOREIGN KEY REFERENCES POS_ServedAs (ServedAsID),
	
	IsQuantified BIT NOT NULL,
	Quantity DECIMAL(18, 4) NOT NULL,

	FK_CreatedUserID INT NOT NULL FOREIGN KEY REFERENCES Users (UserID),
	FK_UpdatedUserID INT NULL FOREIGN KEY REFERENCES Users (UserID),
	DateCreated DATETIME NOT NULL DEFAULT (GETDATE()),
	DateUpdated DATETIME NULL
)